In [1]:
!pip install numpy

In [8]:
import numpy as np

In [3]:
lista=[1,2,3]

In [12]:
matriz = np.array(lista)

In [13]:
matriz

array([1, 2, 3])

In [14]:
type(matriz)

numpy.ndarray

In [15]:
matriz.ndim


1

In [16]:
matriz.shape

(3,)

In [17]:
lista3=[1.0,True,"a",3]

matriz3

In [18]:
matriz3=np.array(lista3)

In [19]:
matriz3

array(['1.0', 'True', 'a', '3'], dtype='<U32')

In [20]:
print(matriz.dtype)

int32


In [21]:
print(matriz3.dtype)

<U32


## Matrices solo pueden tener 1 tipo de dato

In [22]:
3*True

3

In [23]:
matriz4=np.array([1,2,3], dtype="float")

In [24]:
matriz4

array([1., 2., 3.])

In [25]:
matriz4.dtype

dtype('float64')

In [26]:
matriz5=np.array([1,2,3], dtype="float16")

In [27]:
matriz5.dtype

dtype('float16')

## Operaciones con matrices

In [28]:
m=[1,2,3]
n=[3,4,5]

In [33]:
m+n #la lista concatena su contenido

[1, 2, 3, 3, 4, 5]

In [31]:
matriz_m = np.array(m)
matriz_n = np.array(n)

In [32]:
matriz_m + matriz_n #la matriz suma los elementos en cada posicion

array([4, 6, 8])

In [34]:
np.square(matriz_m)

array([1, 4, 9], dtype=int32)

In [35]:
matriz_m[0]

1

In [36]:
matriz_m[-1]

3

In [37]:
matriz_m[0] = True

In [38]:
matriz_m

array([1, 2, 3])

In [39]:
matriz_m[1] = True

In [40]:
matriz_m

array([1, 1, 3])

In [41]:
matriz_m[1] = "True"

ValueError: invalid literal for int() with base 10: 'True'

In [42]:
matriz_o=np.array([6,7,8,9])

In [43]:
matriz_o

array([6, 7, 8, 9])

In [44]:
matriz_m+matriz_o

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [45]:
matriz_m-matriz_o

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [46]:
matriz_m-matriz_n

array([-2, -3, -2])

In [47]:
np.absolute(matriz_m-matriz_n)

array([2, 3, 2])

In [48]:
np.maximum(matriz_m,matriz_n)

array([3, 4, 5])

In [49]:
np.minimum(matriz_m,matriz_n)

array([1, 1, 3])

In [50]:
matriz_m

array([1, 1, 3])

In [51]:
matriz_n

array([3, 4, 5])

In [52]:
np.minimum(matriz_m,matriz_o)

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [53]:
desordenada=np.array([5,21,8,2,77,38,-90])

In [54]:
desordenada

array([  5,  21,   8,   2,  77,  38, -90])

In [55]:
desordenada.sort()
desordenada

array([-90,   2,   5,   8,  21,  38,  77])

In [56]:
m1=np.array(range(1,6))
m2=np.array(range(4,11))

In [57]:
m1

array([1, 2, 3, 4, 5])

In [58]:
m2

array([ 4,  5,  6,  7,  8,  9, 10])

In [61]:
m3 = np.append(m1,m2)

In [62]:
m3

array([ 1,  2,  3,  4,  5,  4,  5,  6,  7,  8,  9, 10])

In [63]:
np.insert(m3,2,11,axis=0)

array([ 1,  2, 11,  3,  4,  5,  4,  5,  6,  7,  8,  9, 10])

In [64]:
v=np.array(range(3,35))

In [65]:
v

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34])

In [69]:
a=np.array(range(5))
a=np.append(a,a)

In [70]:
a

array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4])

In [78]:
a.sort()

In [79]:
a

array([0, 0, 1, 1, 2, 2, 3, 3, 4, 4])

In [83]:
a=np.array(list(range(5))+list(range(5)))

In [84]:
a2

array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4])

# Matrices bidimensionales

In [85]:
b=np.array([[18,23,30],[400,380,710]])

In [86]:
b

array([[ 18,  23,  30],
       [400, 380, 710]])

In [87]:
type(b)

numpy.ndarray

In [88]:
b.shape #dimensiones de la matriz

(2, 3)

In [89]:
b.ndim # n dimensiones

2

In [90]:
b[-1,-1]

710

In [91]:
b[0,0]

18

In [94]:
np.resize(b,(10,10))

array([[ 18,  23,  30, 400, 380, 710,  18,  23,  30, 400],
       [380, 710,  18,  23,  30, 400, 380, 710,  18,  23],
       [ 30, 400, 380, 710,  18,  23,  30, 400, 380, 710],
       [ 18,  23,  30, 400, 380, 710,  18,  23,  30, 400],
       [380, 710,  18,  23,  30, 400, 380, 710,  18,  23],
       [ 30, 400, 380, 710,  18,  23,  30, 400, 380, 710],
       [ 18,  23,  30, 400, 380, 710,  18,  23,  30, 400],
       [380, 710,  18,  23,  30, 400, 380, 710,  18,  23],
       [ 30, 400, 380, 710,  18,  23,  30, 400, 380, 710],
       [ 18,  23,  30, 400, 380, 710,  18,  23,  30, 400]])

In [93]:
np.resize(b,(2,3))

array([[ 18,  23,  30],
       [400, 380, 710]])

In [95]:
f=np.arange(1,10,2)

In [96]:
f

array([1, 3, 5, 7, 9])

In [97]:
g=np.arange(1,10)

In [98]:
g

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [100]:
gg=np.array([g,g])

In [101]:
gg

array([[1, 2, 3, 4, 5, 6, 7, 8, 9],
       [1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [103]:
h=np.reshape(np.array(range(1,26)),(5,5))

In [104]:
h

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [105]:
h.shape

(5, 5)

In [106]:
i=np.asarray([1,2,3])
i

array([1, 2, 3])

In [107]:
type(i)

numpy.ndarray

In [109]:
i.dtype

dtype('int32')

In [110]:
j=i.astype("complex64") #cambio de tipo

In [111]:
j.dtype

dtype('complex64')

In [112]:
j

array([1.+0.j, 2.+0.j, 3.+0.j], dtype=complex64)

In [116]:
k=i.astype("float64")

In [117]:
k

array([1., 2., 3.])

In [118]:
k.dtype

dtype('float64')

In [119]:
type(k)

numpy.ndarray

In [120]:
np.eye(2, dtype=int)

array([[1, 0],
       [0, 1]])

In [126]:
np.eye(2,3) #por default es tipo float

array([[1., 0., 0.],
       [0., 1., 0.]])

In [127]:
np.eye(2,3, dtype=int)

array([[1, 0, 0],
       [0, 1, 0]])

In [128]:
np.eye(2,3,1)

array([[0., 1., 0.],
       [0., 0., 1.]])

In [129]:
np.eye(10,7,3, dtype=int)

array([[0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]])

In [131]:
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [132]:
np.zeros(3)

array([0., 0., 0.])

In [133]:
np.ones([3,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [134]:
np.ones(3)

array([1., 1., 1.])

In [149]:
np.ones(shape=(2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [136]:
np.empty(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [141]:
np.empty(shape=(2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [148]:
np.empty(shape=(2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [143]:
np.full(shape=(2,8), fill_value=False)

array([[False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False]])

In [150]:
np.identity(4) #matriz identidad siempre es cuadrada y siempre tiene 1s en diagonal

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [153]:
np.resize(range(9),(3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [152]:
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])